export const enum Feature {
    LEVEL_DESERT = 'LEVEL_DESERT',

    FENCE_MESH_WIRE = 'FENCE_MESH_WIRE',

    FENCE_LASER = 'FENCE_LASER',

    FENCE_MODERN_BARBED_WIRE = 'FENCE_MODERN_BARBED_WIRE',

    FENCE_RUSTY_BARBED_WIRE = 'FENCE_RUSTY_BARBED_WIRE'

}
